### ISSUE TITLE
VOXELFORMAT: GLTF: support exporting palette materials

### ISSUE THREAD

**Issue by mgerhardy** [vengi-voxel/vengi#402]
1a9c6763fd9e7f87b080da31dbc1e682e59773a6 added material support to the palette (`palette::Palette`) - formats like gltf should now also export (and maybe even import if possible) these values into the `palette::Material` structure.

* https://github.khronos.org/glTF-Validator/
* https://sandbox.babylonjs.com/

This property is not yet handled, too: https://github.com/jpaver/opengametools/issues/64

The test file was kindly provided by AbductedbyPixel and is available at `data/tests/test_material.vox`

[Enterprise PBR Shading Model](https://dassaultsystemes-technology.github.io/EnterprisePBRShadingModel/user_guide.md.html) - https://github.com/DassaultSystemes-Technology/EnterprisePBRShadingModel

# Links

* https://magicavoxel.fandom.com/wiki/Matter_panel_(interface)
* https://magicavoxel.fandom.com/wiki/Material_(interface)
* https://magicavoxel.fandom.com/wiki/Diffuse_(interface)
* https://magicavoxel.fandom.com/wiki/Plastic_(interface)
* https://magicavoxel.fandom.com/wiki/Metal_(interface)
* https://magicavoxel.fandom.com/wiki/Cloud_(interface)
* https://magicavoxel.fandom.com/wiki/Glass_(interface)
* https://magicavoxel.fandom.com/wiki/Emission_(interface)

# TODO

- [ ] Find sane default values for the `palette::Material` properties
- [ ] Complete the list of magicavoxel material properties and their gltf match (if any)
- [x] Allow to disable material export via cvar

# Material mappings

This table is here to understand and map the mv material settings from ogt_vox to gltf

| Description                 | MV Material           | Magicavoxel     | MV Default     | MV Value Range UI | MV default UI |     | GLTF                                | GLTF Default Value  | GLTF Value Range | GLTF Link | Magicavoxel Link |
| --------------------------- | --------------------- | --------------- | -------------- | ----------------- | ------------- | --- | ----------------------------------- | ------------------- | ---------------- | --------- | ---------------- |
| Index of Refraction         | glass                 | ior             | 1.3            | 1.0,3.0           | 1.0-3.0       | 1.3 | KHR_materials_ior                   | 1.5                 | [1.0, ∞)         | https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_ior | |
| Specular Intensity          | metal, plastic        | spec            | 0.5            | 0.0,1.0           | 0-100         | 50  | KHR_materials_specular              | 1.0                 | [0.0, 1.0]       | https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_specular | https://magicavoxel.fandom.com/wiki/Metal_(interface) |
| Glossiness                  |                       | g               | -              |                   | -             |     | KHR_materials_pbrSpecularGlossiness | 1.0                 | [0.0, 1.0]       | https://kcoley.github.io/glTF/extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness/ | |
| Roughness                   | glass, metal, plastic | rough           | 0.1            | 0.0,1.0           | 0-100         | 10  | KHR_materials_pbrSpecularGlossiness | 0.5                 | [0.0, 1.0]       | https://kcoley.github.io/glTF/extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness/ | https://magicavoxel.fandom.com/wiki/Metal_(interface) |
| Roughness                   | glass, metal, plastic | rough           | 0.1            | 0.0,1.0           | 0-100         | 10  | pbrMetallicRoughness                | 0.5                 | [0.0, 1.0]       | | https://magicavoxel.fandom.com/wiki/Metal_(interface) |
| density                     | blend, glass, clouds  | d               | 0              | 0.0,1.0           | 0-100         | 0   | KHR_materials_pbrSpecularGlossiness | 255, 255, 255       | RGB [0, 255]     | https://kcoley.github.io/glTF/extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness/ | |
| Emission Intensity          | emission              | emit            | 0              | 0.0,1.0           | 0-100         |     | Emission texture                    | 0.0                 | [0.0, 1.0]       | | |
| Alpha                       |                       | alpha           | -              |                   | -             |     | alpha in base color texture         | 1.0                 | [0.0, 1.0]       | | |
| Transmission/Transparency   | glass, blend          | trans           | 0              | 0.0,1.0           | 0-100         |     |                                     | -                   | -                | | |
| Metallic                    | metal                 | metal           | 0              | 0.0,1.0           | 0-100         |     | pbrMetallicRoughness                | 0.0                 | [0.0, 1.0]       | | https://magicavoxel.fandom.com/wiki/Metal_(interface) |
| Attenuation                 | glass                 | att             | 0              | 0.0,1.0           | 0-100         |     | KHR_materials_volume                | 1,1,1 (color value) | -                | https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_volume | |
| Radiant flux (Power)        | emission              | flux            | 0              | 0.0,4.0           | 1-5           |     | -                                   | -                   | -                | | |
| Low Dynamic Range           | emission              | ldr             | 0              | 0.0,1.0           | 0-100         |     | -                                   | -                   | -                | | |
| Spherical                   |                       | sp              | -              | 0.0,5.0           | 0-5           |     | -                                   | -                   | -                | | |
| Media                       |                       | media           | -              | 1,2,3             | -             |     | -                                   | -                   | -                | | |
| Phase Mix                   | blend, glass, cloud   | ??              | 0.0            | -0.9,0.9          | -0.9 - +0.9   | 70  | -                                   | -                   | -                | | |
| | blend, glass, cloud       | media_type            | _scatter, _emit |                |                   |               |     |                                     |                     |                  | | |
| Plastic? is this media?     |                       |                 |                |                   |               |     |                                     |                     |                  | | |

# From MV changelog:

>  New Unified Material System[06/30/2020]
>  * Blend Material: weighted blending Metal/Plastic/Glass/Cloud materials (similar to Disney Principled BRDF).
>  * SSS Material: sub-surface scattering. transparency tp control light transmission. density to control light scattering.
>  * Aborb/Scatter/Emissive Media Material: emissive cloud. can be contained in the glass with ior > 1.
>  * Improved Alpha Blending: glass material, absorb media type, density = 0, ior = 0, transparency > 0

# A list of property key/value pairs of a huge vox file repository

* [magicavoxel-property-keys-incl.rOBJ.txt](https://github.com/user-attachments/files/18748713/magicavoxel-property-keys-incl.rOBJ.txt)
* [magicavoxel-property-keys.txt](https://github.com/user-attachments/files/18748712/magicavoxel-property-keys.txt)

# A list of material values from a huge vox file repository.

* [all_materials_uniq.txt](https://github.com/user-attachments/files/18757770/all_materials_uniq.txt)

**Comment by mgerhardy** [comment]
two new cvars were added: `voxformat_gltf_khr_materials_pbrspecularglossiness` and `voxformat_gltf_khr_materials_specular`. They control which extension you want to use to save the specular material values in the gltf file. There will at least be one other cvar to control whether you want to export materials at all.

**Comment by mgerhardy** [comment]
| Magicavoxel | GLTF |
| - | - |
| ior | KHR_materials_ior |
| spec | KHR_materials_specular or KHR_materials_pbrSpecularGlossiness |
| g | KHR_materials_pbrSpecularGlossiness (`glossinessFactor`) |
| rough | KHR_materials_pbrSpecularGlossiness (`glossinessFactor`: `1 - rough`) or `pbrMetallicRoughness (roughnessFactor)` |
| d | KHR_materials_pbrSpecularGlossiness (`diffuseFactor`) |
| emit | emission texture |
| alpha | included as alpha component in base color texture |
| metal | `pbrMetallicRoughness (metallicFactor)` |

**Comment by mgerhardy** [comment]
https://github.com/AstrorEnales/blender_magicavoxel/issues/1 some useful information here

**Comment by mgerhardy** [comment]
## Vengi Material Properties

All properties are `float`. A bitmask tracks which are actively set (bit set when value > 0).

| # | Property | Internal Name | Range | Default | MagicaVoxel Origin |
|---|----------|---------------|-------|---------|--------------------|
| 1 | MaterialMetal | `metal` | 0.0-1.0 | 0.0 | metal |
| 2 | MaterialRoughness | `roughness` | 0.0-1.0 | 0.1 | glass, metal, plastic |
| 3 | MaterialSpecular | `specular` | 0.0-1.0 | 0.0 | metal, plastic |
| 4 | MaterialIndexOfRefraction | `indexOfRefraction` | 1.0-3.0 | 1.3 | glass (ior) |
| 5 | MaterialAttenuation | `attenuation` | 0.0-1.0 | 0.0 | glass (att) |
| 6 | MaterialFlux | `flux` | 0.0-1.0 | 0.0 | emission (flux) |
| 7 | MaterialEmit | `emit` | 0.0-1.0 | 0.0 | emission (emit) |
| 8 | MaterialLowDynamicRange | `lowDynamicRange` | 0.0-1.0 | 0.0 | emission (ldr) |
| 9 | MaterialDensity | `density` | 0.0-1.0 | 0.0 | blend, glass, clouds |
| 10 | MaterialSp | `sp` | 0.0-1.0 | 0.0 | spherical |
| 11 | MaterialPhase | `phase` | 0.0-1.0 | 0.0 | scattering asymmetry (g) |
| 12 | MaterialMedia | `media` | 0.0-1.0 | 0.0 | media type |

Alpha is NOT a MaterialProperty - it lives in the RGBA color channel directly.

## Best Material Mappings

### Recommended mapping (validated against current code and glTF spec)

| Vengi Property | glTF Target | Extension | Direction | Quality | Notes |
|---|---|---|---|---|---|
| **MaterialMetal** | `pbrMetallicRoughness.metallicFactor` | Core PBR | Bidirectional | Exact | Direct 1:1 mapping, same semantics and range |
| **MaterialRoughness** | `pbrMetallicRoughness.roughnessFactor` | Core PBR | Bidirectional | Exact | Direct 1:1 mapping, same semantics and range |
| **MaterialEmit** | `emissiveFactor[0,1,2]` (uniform RGB) | Core PBR | Bidirectional | Good | Save: uniform across RGB. Load: only reads channel 0. Per-color emit via emissive texture |
| **MaterialSpecular** | `specularFactor` | `KHR_materials_specular` | Bidirectional | Good | Save: multiplied by color RGB. Load: scalar value. Alternatively via `KHR_materials_pbrSpecularGlossiness` |
| **MaterialIndexOfRefraction** | `ior` | `KHR_materials_ior` | Bidirectional | Exact | Direct 1:1 mapping. MV range 1.0-3.0, glTF range [1.0, inf) |
| **MaterialAttenuation** | `attenuationColor` | `KHR_materials_volume` | Export only | Lossy | Save: color * attenuation. No load handler exists. Should also map `attenuationDistance` |
| **MaterialDensity** | `diffuseFactor` | `KHR_materials_pbrSpecularGlossiness` | Export only | Lossy | Save: color * density. Load: parsed but discarded (TODO) |
| **MaterialPhase** | `glossinessFactor` | `KHR_materials_pbrSpecularGlossiness` | Bidirectional | Approximate | MV: scattering asymmetry. glTF: glossiness. Semantically different but used as best-fit |
| **MaterialEmit** (strength) | `emissiveStrength` | `KHR_materials_emissive_strength` | Import only | Good | Load: multiplied into emit. Save: disabled (`#if 0`) |
| **Alpha** (color.a) | `alphaMode` + base color alpha | Core PBR | Export only | Good | Save: BLEND if alpha < 255. Load: not read back |
| **MaterialFlux** | - | - | - | No match | MV-specific radiant flux. No glTF equivalent. Could map to `emissiveStrength` as approximation |
| **MaterialLowDynamicRange** | - | - | - | No match | MV-specific LDR flag. No glTF equivalent |
| **MaterialSp** | - | - | - | No match | MV-specific spherical parameter. No glTF equivalent |
| **MaterialMedia** | - | - | - | No match | MV-specific media type. No glTF equivalent |

### Proposed new mappings (not yet implemented)

| Vengi Property | Proposed glTF Target | Extension | Rationale |
|---|---|---|---|
| **Alpha / trans** | `transmissionFactor` | `KHR_materials_transmission` | MV transparency maps naturally to glTF transmission. Currently not implemented at all |
| **MaterialFlux** | `emissiveStrength` | `KHR_materials_emissive_strength` | Flux controls emission power, emissiveStrength scales emission intensity. Best available approximation: `emissiveStrength = 1.0 + flux * 4.0` |
| **MaterialAttenuation** | `attenuationDistance` + `attenuationColor` | `KHR_materials_volume` | Currently only writes attenuationColor. Should also write attenuationDistance derived from attenuation factor |
| **MaterialDensity** | `thicknessFactor` | `KHR_materials_volume` | Density controls how much light scatters through the volume. thickness is the closest glTF concept |

## Current Implementation Status

### Export (vengi to glTF)

| Property | Status | Code Location |
|---|---|---|
| Metal | Implemented | `generateMaterials()` - `pbrMetallicRoughness.metallicFactor` |
| Roughness | Implemented | `generateMaterials()` - `pbrMetallicRoughness.roughnessFactor` |
| Emit | Implemented | `generateMaterials()` - `emissiveFactor` + emissive texture |
| Specular | Implemented (opt-in) | `save_KHR_materials_specular()` or `save_KHR_materials_pbrSpecularGlossiness()` |
| IndexOfRefraction | Implemented | `save_KHR_materials_ior()` |
| Attenuation | Implemented (partial) | `save_KHR_materials_volume()` - only attenuationColor, missing attenuationDistance |
| Density | Implemented | `save_KHR_materials_pbrSpecularGlossiness()` - as diffuseFactor |
| Phase | Implemented | `save_KHR_materials_pbrSpecularGlossiness()` - as glossinessFactor |
| Emissive Strength | Disabled | `save_KHR_materials_emissive_strength()` - `#if 0` |
| Alpha | Implemented | `generateMaterials()` - alphaMode BLEND/OPAQUE |
| Flux | Not implemented | No glTF target |
| LowDynamicRange | Not implemented | No glTF target |
| Sp | Not implemented | No glTF target |
| Media | Not implemented | No glTF target |

### Import (glTF to vengi)

| glTF Property | Status | Code Location |
|---|---|---|
| metallicFactor | Implemented | `loadMaterial()` |
| roughnessFactor | Implemented | `loadMaterial()` |
| emissiveFactor | Implemented (partial) | `loadMaterial()` - only reads channel 0 |
| emissiveStrength | Implemented | `load_KHR_materials_emissive_strength()` |
| specularFactor (KHR_materials_specular) | Implemented | `load_KHR_materials_specular()` |
| specularColorFactor | Parsed, not used | `load_KHR_materials_specular()` - TODO |
| ior | Implemented | `load_KHR_materials_ior()` |
| glossinessFactor | Implemented | `load_KHR_materials_pbrSpecularGlossiness()` |
| specularFactor (pbrSpecGloss) | Implemented (lossy) | `load_KHR_materials_pbrSpecularGlossiness()` - uses r*g*b product |
| diffuseFactor | Parsed, not used | `load_KHR_materials_pbrSpecularGlossiness()` - TODO |
| diffuseTexture | Parsed, not used | `load_KHR_materials_pbrSpecularGlossiness()` - TODO |
| specularGlossinessTexture | Parsed, not used | `load_KHR_materials_pbrSpecularGlossiness()` - TODO |
| attenuationColor/Distance | Not implemented | No load handler for KHR_materials_volume |
| transmissionFactor | Not implemented | KHR_materials_transmission not handled |
| alphaMode | Not imported | Not read back into palette |
| baseColorFactor | Not imported | TODO in loadMaterial() |

## Round-trip Fidelity

| Property | Save | Load | Round-trip |
|---|---|---|---|
| Metal | OK | OK | Lossless |
| Roughness | OK | OK | Lossless |
| Emit | OK (uniform RGB) | OK (R only) | Lossless (since save is uniform) |
| Specular | OK (color * spec) | OK (scalar or r*g*b) | Lossy - color multiplication not reversed |
| IndexOfRefraction | OK | OK | Lossless |
| Attenuation | OK (export) | Missing | Broken - no import |
| Density | OK (as diffuseFactor) | Missing | Broken - parsed but discarded |
| Phase | OK (as glossiness) | OK | Lossless |
| Flux | Missing | Missing | N/A |
| LowDynamicRange | Missing | Missing | N/A |
| Sp | Missing | Missing | N/A |
| Media | Missing | Missing | N/A |
| Alpha | OK (alphaMode) | Missing | Broken - not read back |
| Emissive Strength | Disabled (#if 0) | OK | One-way import only |

## Recommendations

### High priority (broken round-trips)

1. **Import KHR_materials_volume**: Add `load_KHR_materials_volume()` to read `attenuationColor` back into `MaterialAttenuation`
2. **Import diffuseFactor**: Map `KHR_materials_pbrSpecularGlossiness.diffuseFactor` back to `MaterialDensity`
3. **Import alphaMode**: Read `alphaMode == "BLEND"` and set color alpha accordingly
4. **Enable emissive strength export**: Un-`#if 0` the `save_KHR_materials_emissive_strength()` function

### Medium priority (new mappings)

5. **Add KHR_materials_transmission**: Map MV `trans`/alpha to `transmissionFactor` for glass-like materials
6. **Map flux to emissiveStrength**: Use `emissiveStrength = 1.0 + flux * scale` as approximation
7. **Fix specular round-trip**: On import, divide specularFactor by color to recover the original scalar value

### Low priority (no glTF equivalent)

8. **LowDynamicRange, Sp, Media**: These are MagicaVoxel-specific. Consider storing in glTF `extras` for lossless round-trip with vengi, but they won't be understood by other glTF viewers

## Extension Interaction

The current code has a mutually exclusive relationship between two specular models:

```
if (cfg::VoxformatGLTF_KHR_materials_pbrSpecularGlossiness == true)
    -> writes KHR_materials_pbrSpecularGlossiness (density, specular, phase/roughness)
    -> skips KHR_materials_specular, KHR_materials_ior, KHR_materials_volume
else
    -> writes KHR_materials_specular + KHR_materials_ior + KHR_materials_volume
```

Note: `KHR_materials_pbrSpecularGlossiness` is a deprecated extension. The Khronos Group recommends using the metallic-roughness model with `KHR_materials_specular` and `KHR_materials_ior` instead. Consider making the non-deprecated path the default.
